# docker-compose.override.yml
# Developer-friendly overrides applied on top of docker-compose.yml.
# Compose automatically loads this file (no extra flags needed).
# - Mount source code for live edits
# - Add sensible restart policies

services:
  api:
    volumes:
      - ./:/code
    restart: unless-stopped

  scheduler:
    volumes:
      - ./:/code
    restart: unless-stopped

  worker:
    volumes:
      - ./:/code
    restart: unless-stopped
