services:
  api:
    env_file:
      - .env
    environment:
      - MEDIA_BACKEND=${MEDIA_BACKEND}
      - STORAGE_BACKEND=${STORAGE_BACKEND}
      - S3_PROVIDER=${S3_PROVIDER}
      - S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
      - S3_REGION=${S3_REGION}
      - S3_BUCKET=${S3_BUCKET}
      - S3_PREFIX=${S3_PREFIX}
      - S3_PUBLIC_BASE_URL=${S3_PUBLIC_BASE_URL}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}

  worker:
    env_file:
      - .env
    environment:
      - MEDIA_BACKEND=${MEDIA_BACKEND}
      - STORAGE_BACKEND=${STORAGE_BACKEND}
      - S3_PROVIDER=${S3_PROVIDER}
      - S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
      - S3_REGION=${S3_REGION}
      - S3_BUCKET=${S3_BUCKET}
      - S3_PREFIX=${S3_PREFIX}
      - S3_PUBLIC_BASE_URL=${S3_PUBLIC_BASE_URL}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
